DM_FLAGS=%DM_FLAGS%
DM_LIB=%DM_LIB%
CC=%CC%

CUNIT_LIB=../lib/libcunit.a
CUNIT_INC=../include/CUnit


CFLAGS=-Wall -Werror -g $(DM_FLAGS) -I../include %INCLUDES% %CFLAGS%
LDFLAGS=-g %CFLAGS%
LIBDEPS=../src/standard/libops_std.a ../src/advanced/libops_adv.a
LIBS=$(LIBDEPS) %CRYPTO_LIBS% %ZLIB% $(DM_LIB) $(CUNIT_LIB)

TESTSRC=tests.c \
                test_packet_types.c \
                test_crypt_mpi.c test_rsa_decrypt.c test_rsa_encrypt.c \
                test_crypto.c

TESTOBJ=$(TESTSRC:.c=.o)

all: Makefile $(CUNIT_LIB) .depend tests

tests: $(CUNIT_LIB) $(TESTOBJ) $(LIBDEPS)
	$(CC) $(LDFLAGS) -o tests $(TESTOBJ) $(LIBS)

$(CUNIT_LIB):
	tar xvfz CUnit-2.1-0-src.tar.gz
	(cd CUnit-2.1-0 && ./configure --prefix $(PWD)/../ && make && make install)

clean:
	rm -f $(EXES) *.o *.i
	rm -rf testdir.*
	rm -f TAGS

.depend: *.[ch] ../include/openpgpsdk/*.h $(CUNIT_INC)

	$(CC) $(CFLAGS) -E -M *.c > .depend

force_depend:
	$(CC) $(CFLAGS) -E -M *.c > .depend

Makefile: Makefile.template ../configure
	echo Makefile is older than templates, rerun configure
	exit 1

