DM_FLAGS=%DM_FLAGS%
DM_LIB=%DM_LIB%
CC=%CC%

CUNIT_LIB=../lib/libcunit.a
CUNIT_INC=../include/CUnit


CFLAGS=-Wall -Werror -g $(DM_FLAGS) -I../include %INCLUDES% %CFLAGS%
LDFLAGS=-g %CFLAGS%
LIBDEPS=../lib/libops.a
LIBS=$(LIBDEPS) %CRYPTO_LIBS% %ZLIB% $(DM_LIB) $(CUNIT_LIB)

COMMONTESTSRC= test_packet_types.c \
                test_crypt_mpi.c test_rsa_decrypt.c test_rsa_encrypt.c \
                test_rsa_signature.c test_rsa_verify.c \
                test_crypto.c test_common.c
COMMONTESTOBJ=$(COMMONTESTSRC:.c=.o)

TESTSRC= tests.c 
TESTOBJ= $(TESTSRC:.c=.o)

GPGTESTSRC= tests_gpg.c
GPGTESTOBJ= $(GPGTESTSRC:.c=.o)

all: Makefile $(CUNIT_LIB) .depend tests tests_gpg

tests: $(CUNIT_LIB) $(TESTOBJ) $(COMMONTESTOBJ) $(LIBDEPS)
	$(CC) $(LDFLAGS) -o tests $(TESTOBJ) $(COMMONTESTOBJ) $(LIBS)

tests_gpg: $(CUNIT_LIB) $(GPGTESTOBJ) $(COMMONTESTOBJ) $(LIBDEPS)
	$(CC) $(LDFLAGS) -o tests_gpg $(GPGTESTOBJ) $(COMMONTESTOBJ) $(LIBS)

$(CUNIT_LIB):
	tar xvfz CUnit-2.1-0-src.tar.gz
	(cd CUnit-2.1-0 && ./configure --prefix $(PWD)/../ && make && make install)

clean:
	rm -f $(EXES) *.o *.i
	rm -rf testdir.*
	rm -f TAGS

.depend: *.[ch] ../include/openpgpsdk/*.h $(CUNIT_INC)

	$(CC) $(CFLAGS) -E -M *.c > .depend

force_depend:
	$(CC) $(CFLAGS) -E -M *.c > .depend

Makefile: Makefile.template ../configure
	echo Makefile is older than templates, rerun configure
	exit 1

